# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-jetson-headunit"
BBFILE_PATTERN_meta-jetson-headunit = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-jetson-headunit = "10"

LAYERDEPENDS_meta-jetson-headunit = "core tegra qt5-layer openembedded-layer meta-middleware"
LAYERSERIES_COMPAT_meta-jetson-headunit = "kirkstone"
